### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bilyboy785** [xataz/docker-lufi#1]
Salut ! Je souhaiterai utiliser ton docker Lufi mais lorsqu'il démarre j'ai une erreur 502. 

Voici la conf que Jwilder génère : https://paste.bouillaudmartin.fr/?2228dfb0141c75ab#k+ruDWUAKb1xGpZMO3qbHPw7xoQwhLI6kEvZt5rYlWs=

Je ne comprends au passage pas pourquoi au niveau de l'Upstream il me met down au lieu du port..

Voici le docker-compose pour lufi : https://paste.bouillaudmartin.fr/?5bf1b42bd6b26cdf#5FQFsRp3GhMi6s+wQ4Y7ocmRQ8xtrAhrOEtjJDNRoV0=

Si jamais tu as une idée ..

Merci ;)

**Comment by bilyboy785** [comment]
Problème réglé : j'ai EXPOSE le port, et tout fonctionne nickel !

Pour ceux qui veulent la solution : https://paste.bouillaudmartin.fr/?6320915b932f32af#uVl5HW3ePOU6TV6opLrPVHWLMjr2tGmS3hWc6r31Nx0=

**Comment by xataz** [comment]
Salut,

Normalement tu n'as pas besoin d'expose le port, je ne connais pas le reverse de jwilder, mais il me semble qu'il cherche le port expose sur le conteneur, et s'il n'existe pas il utilise le port 80. mais un truc comme ça devrais fonctionner : 

```shell


    lufi-martin:
        restart: always
        image: xataz/lufi
        container_name: lufi-martin
        environment:
          - UID=1000
          - GID=1000
          - WEBROOT=/
          - SECRET=0423bab3aea2d87d5eedd9a4e8173618
          - MAX_FILE_SIZE=250000000
          - CONTACT=contact@bouillaudmartin.fr
          - VIRTUAL_HOST=upload.bouillaudmartin.fr
          - LETSENCRYPT_HOST=upload.bouillaudmartin.fr
          - LETSENCRYPT_EMAIL=contact@bouillaudmartin.fr
          - VIRTUAL_PORT=8080
        volumes:
          - /home/martinbouillaud/dockers/lufi/data:/usr/lufi/data
          - /home/martinbouillaud/dockers/lufi/files:/usr/lufi/files
```

**Comment by xataz** [comment]
As tu eu l'occasion de tester ma solution ?

**Comment by xataz** [comment]
Pas de réponse depuis plus d'un mois, je clos donc l'issue
