### ISSUE TITLE
[HELP] Impossible de se connecter 

### ISSUE THREAD

**Issue by gudbes** [xataz/docker-lufi#2]
Bonjour,

J'essaye de mettre en place ton "docker-lufi" mais je bloque. 
C'est ma première utilisation de docker car j'en entend parler mais j'avais jamais mis le nez dedans :)
Je travaille sur une V.M. sous debian Stretch. J'ai installer docker via le tuto de leur site.

Voila mes dernières commandes : 
```
$ sudo docker pull xataz/lufi
$ sudo docker run -d -p 8080:8080 xataz/lufi
```
mais lorsque je lance un http://127.0.0.1:8080, on m'indique la connexion a échoué. Je me suis interrogé, à savoir qu'il faut peut être installé nginx sur ma V.M. mais après l'installation pas de changement. Il doit, heu non, il me manque quelque chose mais je ne vois pas où.
Pourras tu, s'il te plaît, éclairer ma lanterne.

En te remerciant par avance.

gudbes

**Comment by xataz** [comment]
Salut,

Désolé pour le temps de réponse.
L'image est actuellement totalement fonctionnel, pourrais-tu refaire un essai ?

**Comment by gudbes** [comment]
Salut @xataz  Merci pour ta réponse, je vais essayé de tester ça dans les jours à venir

**Comment by gudbes** [comment]
J'ai donc fait comme j'ai indiqué dans mon premier post et malheureusement j'ai toujours le message quand j'essaye de mon connecter en local : la connexion a échoué.

**Comment by xataz** [comment]
Si je comprends bien, tu fais tourner lufi dans une VM qui est sur ta machine ?
Dans ce cas il faudrait que tu utilises l'adresse IP de la VM

**Comment by gudbes** [comment]
@xataz 
La VM c'est pour faire le test avant deploiement ... Je viens de mettre en place le docker xataz/lutim et lui fonctionne bien mais j'aimerai mettre en place le lufi :/

**Comment by xataz** [comment]
Ouh la vilaine erreur que j'ai fait dans le README.

Le port à écouté est le 8081, pas le 8080. Je corrige le readme, c'est ma faute ^^

**Comment by gudbes** [comment]
Je regarde cela et je te confirme ... si c'est que ça ben j'aurais pu chercher plus loin que le bout de mon nez. :D

**Comment by gudbes** [comment]
@xataz C'est bon ça fonctionne :) Pour y accéder de l'extérieur, il y a juste à faire du NAT au niveau de ma box ? ou sais tu s'il faut modifier quelques choses au fichier lufi.conf

edit : y a t il possibilité de le passer en francais ^^

**Comment by xataz** [comment]
Oui pour l'accès via l’extérieur c'est a voir au niveau de la box, après tu peux ajouter un reverse proxy entre les deux.

Pour le français je sais pas s'il est multilangue, a ma connaissance non

**Comment by gudbes** [comment]
@xataz merci de ton aide je galère un peu à mettre en place l'accès extérieur : je tombe sur un 502 bad gateway avec nginx.

Dans ma configuration nginx, j'ai ajouté mon domaine : server_name NomDeMonDomaine; et j'ai mis proxy_pass http://127.0.0.1:8081; (que j'ai vu sur un tuto)

As tu une idée par hasard !!

**Comment by xataz** [comment]
Peux tu fournir toute ta configuration nginx ? Et la commande ou ton docker-compose pour lancer le conteneur.

**Comment by gudbes** [comment]
Voila ma config nginx

```
server {
    listen 80;

    # j'ai changé volontairement mon nom de domaine par lufi.nomdedomaine.com
    server_name lufi.nomdedomaine.com;

    access_log /var/log/nginx/lufi.success.log;
    error_log /var/log/nginx/lufi.error.log;

    location / {
        # Add cache for static files
        if ($request_uri ~* ^/(img|css|font|js)/) {
            add_header Expires "Thu, 31 Dec 2037 23:55:55 GMT";
            add_header Cache-Control "public, max-age=315360000";
        }
        # HTTPS only header, improves security
        #add_header Strict-Transport-Security "max-age=15768000";

        # Adapt this to your configuration (port, subdirectory (see below))
        proxy_pass  http://127.0.0.1:8081;

        # Really important! Lufi uses WebSocket, it won't work without this
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # If you want to log the remote port of the file senders, you'll need that
        proxy_set_header X-Remote-Port $remote_port;

        proxy_set_header X-Forwarded-Proto $scheme;

        # We expect the downstream servers to redirect to the right hostname, so don't do any rewrites here.
        proxy_redirect     off;
    }
}
```
et ma commande pour le lancer est :

`docker run -d -p 8081:8081 xataz/lufi`

Merci @xataz pour ton aide :)

**Comment by gudbes** [comment]
C'est bon je viens de supprimer le lien symbolique avec la commande suivante et tout fonctionne maintenant. 

```
    sudo rm /etc/nginx/sites-enabled/default
    sudo service nginx restart
```

Un grand merci à toi pour ton travail et ton partage et bon continuation.
