### ISSUE TITLE
Mounting themes directory makes the app 404

### ISSUE THREAD

**Issue by m4teh** [xataz/docker-lufi#4]
Great work with the project.

When trying to mount the themes directory as per the direction, app spits 404 "raptor not found" page.

>     volumes:
>       - $PWD/files:/usr/lufi/files
>       - $PWD/data:/usr/lufi/data
>       - $PWD/themes:/usr/lufi/themes

Commenting it out fixes the issue.

**Comment by xataz** [comment]
Hi,

I change volume for custom theme, now it's /themes, not /usr/lufi/themes.
Thanks for this issue
